import static org.junit.Assert.assertEquals;

import dungeon.controller.DungeonGameController;
import dungeon.controller.MonsterDungeonGameController;
import dungeon.model.MonsterDungeonGame;
import dungeon.model.MonsterHuntDungeonGame;
import org.junit.Test;

import java.io.StringReader;

/**
 * Tests DungeonGameController.
 */
public class DungeonGameControllerTest {

  DungeonGameController controller;
  MonsterDungeonGame game;
  Appendable output;

  private void setup(Readable input) {
    game = new MonsterHuntDungeonGame(4, 6, 3, 30, false, 4, true);
    output = new StringBuilder();
    controller = new MonsterDungeonGameController(game, input, output);
  }

  // dungeon created for testing:
  // n: 4, m: 6, connectivity: 3, percent: 30, wrap: false, otyughs: 3, test: true

  //     Expected dungeon layout:
  //     (0, 0) --- (0, 1) --- (0, 2)     (0, 3)     (0, 4) --- (0, 5)
  //                  |                     |          |
  //     (1, 0)     (1, 1) --- (1, 2) --- (1, 3) --- (1, 4) --- (1, 5)
  //       |          |          |                     |          |
  //     (2, 0) --- (2, 1) --- (2, 2)     (2, 3) --- (2, 4)     (2, 5)
  //                  |          |          |                     |
  //     (3, 0) --- (3, 1)     (3, 2) --- (3, 3) --- (3, 4) --- (3, 5)

  // Number of paths: 24 - 1 + 3 = 26
  // Number of treasure caves: (24 - 10 tunnels) * 30% = 14 * (30 / 100) = 4.2 = 5
  // Start Cave: (1, 4)
  // End Cave: (0, 0)
  // Arrow Caves: (0, 1), (0, 5), (1, 0), (1, 2), (1, 5), (2, 0), (3, 0), (3, 3)
  // Otyugh Caves: (0, 0), (0, 3), (1, 1), (3, 0)
  // Treasure Caves: (0, 0), (0, 1), (0, 5), (1, 1), (2, 1)
  // Tunnels: (0, 4), (1, 5), (2, 0), (2, 3), (2, 4), (2, 5), (3, 1), (3, 2), (3, 4), (3, 5)

  /**
   * test that picks arrows, picks treasure, traverses caves and dies.
   */
  @Test
  public void testGamePlayLose() {
    setup(new StringReader("m n m e p m w m s m w s n 1 m n m s s w 1 s w 3 s w 2 s w 1 m w m w "
            + "m n m w"));
    controller.playGame();
    String expected = "\n"
            + "Player can perform 3 actions: Move, Pick and Shoot\n" + "\n"
            + "Press the following keys to control player actions:\n"
            + "'m' - Move, 'p' - Pick, 's' - Shoot\n" + "\n"
            + "Press the following keys to select directions:\n"
            + "'n' - NORTH, 'w' - WEST, 'e' - EAST, 's' - SOUTH\n" + "\n"
            + "Press 'q' to quit the game.\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 4)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n"
            + "Moves: [NORTH, SOUTH, EAST, WEST]\n" + "Arrows: 0\n"
            + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n" + "Smell: FAINT\n"
            + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - NORTH\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (0, 4)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: NONE\n" + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - EAST\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (0, 5)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [WEST]\n"
            + "Arrows: 1\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "Smell: NONE\n" + "\n" + "Select player action:\n" + "\n"
            + "Selected Action - Pick\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (0, 5)\n"
            + "Arrows: 4\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "\n" + "Location Description:\n" + "Moves: [WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: NONE\n" + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - WEST\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (0, 4)\n"
            + "Arrows: 4\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: NONE\n" + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - SOUTH\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 4)\n"
            + "Arrows: 4\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "\n" + "Location Description:\n"
            + "Moves: [NORTH, SOUTH, EAST, WEST]\n" + "Arrows: 0\n"
            + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n" + "Smell: FAINT\n"
            + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - WEST\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 3)\n"
            + "Arrows: 4\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "\n" + "Location Description:\n" + "Moves: [NORTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Enter the direction in which arrow should be shot:\n"
            + "Enter the distance the arrow should travel:\n" + "\n"
            + "Selected Action - Shoot, Direction - NORTH, Distance - 1\n"
            + "Shot: HIT\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 3)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "\n" + "Location Description:\n" + "Moves: [NORTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - NORTH\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (0, 3)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - SOUTH\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 3)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "\n" + "Location Description:\n" + "Moves: [NORTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Enter the direction in which arrow should be shot:\n"
            + "Enter the distance the arrow should travel:\n" + "\n"
            + "Selected Action - Shoot, Direction - WEST, Distance - 1\n"
            + "Shot: MISS\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 3)\n"
            + "Arrows: 2\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "\n" + "Location Description:\n" + "Moves: [NORTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Enter the direction in which arrow should be shot:\n"
            + "Enter the distance the arrow should travel:\n" + "\n"
            + "Selected Action - Shoot, Direction - WEST, Distance - 3\n"
            + "Shot: WASTE\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 3)\n"
            + "Arrows: 1\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "\n" + "Location Description:\n" + "Moves: [NORTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Enter the direction in which arrow should be shot:\n"
            + "Enter the distance the arrow should travel:\n" + "\n"
            + "Selected Action - Shoot, Direction - WEST, Distance - 2\n"
            + "Shot: HIT\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 3)\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "\n" + "Location Description:\n" + "Moves: [NORTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Enter the direction in which arrow should be shot:\n"
            + "Enter the distance the arrow should travel:\n" + "\n"
            + "Selected Action - Shoot, Direction - WEST, Distance - 1\n"
            + "Shot: NOEFFECT\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 3)\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "\n" + "Location Description:\n" + "Moves: [NORTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - WEST\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 2)\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST, WEST]\n"
            + "Arrows: 1\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - WEST\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 1)\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "\n" + "Location Description:\n" + "Moves: [NORTH, SOUTH, EAST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - NORTH\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (0, 1)\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST, WEST]\n"
            + "Arrows: 1\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - WEST\n" + "\n"
            + "Game Over, Status: LOSS\n";
    assertEquals(expected, output.toString());
  }

  /**
   * test that picks arrows, picks treasure, traverses caves and wins.
   */
  @Test
  public void testGamePlayWin() {
    setup(new StringReader("m w m w p s w 1 m w p m n p m e m w s w 1 s w 1 m w"));
    controller.playGame();
    String expected = "\n"
            + "Player can perform 3 actions: Move, Pick and Shoot\n" + "\n"
            + "Press the following keys to control player actions:\n"
            + "'m' - Move, 'p' - Pick, 's' - Shoot\n" + "\n"
            + "Press the following keys to select directions:\n"
            + "'n' - NORTH, 'w' - WEST, 'e' - EAST, 's' - SOUTH\n" + "\n"
            + "Press 'q' to quit the game.\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 4)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n"
            + "Moves: [NORTH, SOUTH, EAST, WEST]\n" + "Arrows: 0\n"
            + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n" + "Smell: FAINT\n"
            + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - WEST\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 3)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [NORTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - WEST\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 2)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST, WEST]\n"
            + "Arrows: 1\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n" + "\n"
            + "Selected Action - Pick\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 2)\n"
            + "Arrows: 4\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Enter the direction in which arrow should be shot:\n"
            + "Enter the distance the arrow should travel:\n" + "\n"
            + "Selected Action - Shoot, Direction - WEST, Distance - 1\n"
            + "Shot: HIT\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 2)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - WEST\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 1)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [NORTH, SOUTH, EAST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n" + "\n"
            + "Selected Action - Pick\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 1)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "\n" + "Location Description:\n" + "Moves: [NORTH, SOUTH, EAST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - NORTH\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (0, 1)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST, WEST]\n"
            + "Arrows: 1\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n" + "\n"
            + "Selected Action - Pick\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (0, 1)\n"
            + "Arrows: 4\n" + "Treasure: DIAMOND: 4, SAPPHIRE: 4, RUBY: 4\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - EAST\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (0, 2)\n"
            + "Arrows: 4\n" + "Treasure: DIAMOND: 4, SAPPHIRE: 4, RUBY: 4\n"
            + "\n" + "Location Description:\n" + "Moves: [WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - WEST\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (0, 1)\n"
            + "Arrows: 4\n" + "Treasure: DIAMOND: 4, SAPPHIRE: 4, RUBY: 4\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Enter the direction in which arrow should be shot:\n"
            + "Enter the distance the arrow should travel:\n" + "\n"
            + "Selected Action - Shoot, Direction - WEST, Distance - 1\n"
            + "Shot: HIT\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (0, 1)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 4, SAPPHIRE: 4, RUBY: 4\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Enter the direction in which arrow should be shot:\n"
            + "Enter the distance the arrow should travel:\n" + "\n"
            + "Selected Action - Shoot, Direction - WEST, Distance - 1\n"
            + "Shot: HIT\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (0, 1)\n"
            + "Arrows: 2\n" + "Treasure: DIAMOND: 4, SAPPHIRE: 4, RUBY: 4\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - WEST\n" + "\n"
            + "Game Over, Status: WIN\n";
    assertEquals(expected, output.toString());
  }

  /**
   * check invalid input to controller.
   */
  @Test
  public void invalidInputs() {
    setup(new StringReader("move north m east 4 w pick shoot s east e one two 2 s w -10 2 m w "
            + "pick p s w one 1 m w m n p s w 1 s w 1 m w"));
    controller.playGame();
    String expected = "\n"
            + "Player can perform 3 actions: Move, Pick and Shoot\n" + "\n"
            + "Press the following keys to control player actions:\n"
            + "'m' - Move, 'p' - Pick, 's' - Shoot\n" + "\n"
            + "Press the following keys to select directions:\n"
            + "'n' - NORTH, 'w' - WEST, 'e' - EAST, 's' - SOUTH\n" + "\n"
            + "Press 'q' to quit the game.\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 4)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n"
            + "Moves: [NORTH, SOUTH, EAST, WEST]\n" + "Arrows: 0\n"
            + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n" + "Smell: FAINT\n"
            + "\n" + "Select player action:\n" + "\n"
            + "Unsupported Operation, Try again.\n" + "\n"
            + "Select player action:\n" + "\n"
            + "Unsupported Operation, Try again.\n" + "\n"
            + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Invalid direction selected. Try again.\n" + "\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Invalid direction selected. Try again.\n" + "\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - WEST\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 3)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [NORTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n" + "\n"
            + "Unsupported Operation, Try again.\n" + "\n"
            + "Select player action:\n" + "\n"
            + "Unsupported Operation, Try again.\n" + "\n"
            + "Select player action:\n"
            + "Enter the direction in which arrow should be shot:\n" + "\n"
            + "Invalid direction selected. Try again.\n" + "\n"
            + "Enter the direction in which arrow should be shot:\n"
            + "Enter the distance the arrow should travel:\n" + "\n"
            + "Distance should be a number. Try again.\n" + "\n"
            + "Enter the distance the arrow should travel:\n" + "\n"
            + "Distance should be a number. Try again.\n" + "\n"
            + "Enter the distance the arrow should travel:\n" + "\n"
            + "Selected Action - Shoot, Direction - EAST, Distance - 2\n"
            + "Shot: MISS\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 3)\n"
            + "Arrows: 2\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [NORTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Enter the direction in which arrow should be shot:\n"
            + "Enter the distance the arrow should travel:\n" + "\n"
            + "Selected Action - Shoot, Direction - WEST, Distance - -10\n" + "\n"
            + "Exception Occurred: Illegal direction/distance\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 3)\n"
            + "Arrows: 2\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [NORTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n" + "\n"
            + "Unsupported Operation, Try again.\n" + "\n"
            + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - WEST\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 2)\n"
            + "Arrows: 2\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST, WEST]\n"
            + "Arrows: 1\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n" + "\n"
            + "Unsupported Operation, Try again.\n" + "\n"
            + "Select player action:\n" + "\n" + "Selected Action - Pick\n"
            + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 2)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Enter the direction in which arrow should be shot:\n"
            + "Enter the distance the arrow should travel:\n" + "\n"
            + "Distance should be a number. Try again.\n" + "\n"
            + "Enter the distance the arrow should travel:\n" + "\n"
            + "Selected Action - Shoot, Direction - WEST, Distance - 1\n"
            + "Shot: HIT\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 2)\n"
            + "Arrows: 2\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - WEST\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 1)\n"
            + "Arrows: 2\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [NORTH, SOUTH, EAST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - NORTH\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (0, 1)\n"
            + "Arrows: 2\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST, WEST]\n"
            + "Arrows: 1\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n" + "\n"
            + "Selected Action - Pick\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (0, 1)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Enter the direction in which arrow should be shot:\n"
            + "Enter the distance the arrow should travel:\n" + "\n"
            + "Selected Action - Shoot, Direction - WEST, Distance - 1\n"
            + "Shot: HIT\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (0, 1)\n"
            + "Arrows: 2\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Enter the direction in which arrow should be shot:\n"
            + "Enter the distance the arrow should travel:\n" + "\n"
            + "Selected Action - Shoot, Direction - WEST, Distance - 1\n"
            + "Shot: HIT\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (0, 1)\n"
            + "Arrows: 1\n" + "Treasure: DIAMOND: 2, SAPPHIRE: 2, RUBY: 2\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - WEST\n" + "\n"
            + "Game Over, Status: WIN\n";
    assertEquals(expected, output.toString());
  }

  /**
   * tests game quits if input stream ends before game is over.
   */
  @Test
  public void endOfInputs() {
    setup(new StringReader("m "));
    controller.playGame();
    String expected = "\n"
            + "Player can perform 3 actions: Move, Pick and Shoot\n" + "\n"
            + "Press the following keys to control player actions:\n"
            + "'m' - Move, 'p' - Pick, 's' - Shoot\n" + "\n"
            + "Press the following keys to select directions:\n"
            + "'n' - NORTH, 'w' - WEST, 'e' - EAST, 's' - SOUTH\n" + "\n"
            + "Press 'q' to quit the game.\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 4)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n"
            + "Moves: [NORTH, SOUTH, EAST, WEST]\n" + "Arrows: 0\n"
            + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n" + "Smell: FAINT\n"
            + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Ran out of inputs, Quitting game.\n";
    assertEquals(expected, output.toString());

    setup(new StringReader("m n"));
    controller.playGame();
    expected = "\n"
            + "Player can perform 3 actions: Move, Pick and Shoot\n" + "\n"
            + "Press the following keys to control player actions:\n"
            + "'m' - Move, 'p' - Pick, 's' - Shoot\n" + "\n"
            + "Press the following keys to select directions:\n"
            + "'n' - NORTH, 'w' - WEST, 'e' - EAST, 's' - SOUTH\n" + "\n"
            + "Press 'q' to quit the game.\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 4)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n"
            + "Moves: [NORTH, SOUTH, EAST, WEST]\n" + "Arrows: 0\n"
            + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n" + "Smell: FAINT\n"
            + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - NORTH\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (0, 4)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: NONE\n" + "\n" + "Select player action:\n" + "\n"
            + "Ran out of inputs, Quitting game.\n";
    assertEquals(expected, output.toString());

    setup(new StringReader("m north p"));
    controller.playGame();
    expected = "\n"
            + "Player can perform 3 actions: Move, Pick and Shoot\n" + "\n"
            + "Press the following keys to control player actions:\n"
            + "'m' - Move, 'p' - Pick, 's' - Shoot\n" + "\n"
            + "Press the following keys to select directions:\n"
            + "'n' - NORTH, 'w' - WEST, 'e' - EAST, 's' - SOUTH\n" + "\n"
            + "Press 'q' to quit the game.\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 4)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n"
            + "Moves: [NORTH, SOUTH, EAST, WEST]\n" + "Arrows: 0\n"
            + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n" + "Smell: FAINT\n"
            + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Invalid direction selected. Try again.\n" + "\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Invalid direction selected. Try again.\n" + "\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Ran out of inputs, Quitting game.\n";
    assertEquals(expected, output.toString());

    setup(new StringReader("m north n s west w -10"));
    controller.playGame();
    expected = "\n"
            + "Player can perform 3 actions: Move, Pick and Shoot\n" + "\n"
            + "Press the following keys to control player actions:\n"
            + "'m' - Move, 'p' - Pick, 's' - Shoot\n" + "\n"
            + "Press the following keys to select directions:\n"
            + "'n' - NORTH, 'w' - WEST, 'e' - EAST, 's' - SOUTH\n" + "\n"
            + "Press 'q' to quit the game.\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 4)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n"
            + "Moves: [NORTH, SOUTH, EAST, WEST]\n" + "Arrows: 0\n"
            + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n" + "Smell: FAINT\n"
            + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Invalid direction selected. Try again.\n" + "\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - NORTH\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (0, 4)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: NONE\n" + "\n" + "Select player action:\n"
            + "Enter the direction in which arrow should be shot:\n" + "\n"
            + "Invalid direction selected. Try again.\n" + "\n"
            + "Enter the direction in which arrow should be shot:\n"
            + "Enter the distance the arrow should travel:\n" + "\n"
            + "Selected Action - Shoot, Direction - WEST, Distance - -10\n" + "\n"
            + "Exception Occurred: Illegal direction/distance\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (0, 4)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: NONE\n" + "\n" + "Select player action:\n" + "\n"
            + "Ran out of inputs, Quitting game.\n";
    assertEquals(expected, output.toString());
  }

  /**
   * test quitting game quits the game.
   */
  @Test
  public void quitGame() {
    setup(new StringReader("m w m w p q"));
    controller.playGame();
    String expected = "\n"
            + "Player can perform 3 actions: Move, Pick and Shoot\n" + "\n"
            + "Press the following keys to control player actions:\n"
            + "'m' - Move, 'p' - Pick, 's' - Shoot\n" + "\n"
            + "Press the following keys to select directions:\n"
            + "'n' - NORTH, 'w' - WEST, 'e' - EAST, 's' - SOUTH\n" + "\n"
            + "Press 'q' to quit the game.\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 4)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n"
            + "Moves: [NORTH, SOUTH, EAST, WEST]\n" + "Arrows: 0\n"
            + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n" + "Smell: FAINT\n"
            + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - WEST\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 3)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [NORTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - WEST\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 2)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST, WEST]\n"
            + "Arrows: 1\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n" + "\n"
            + "Selected Action - Pick\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 2)\n"
            + "Arrows: 4\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [SOUTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n" + "\n"
            + "Game Quit!!!\n";
    assertEquals(expected, output.toString());

    setup(new StringReader("m w p"));
    controller.playGame();
    expected = "\n"
            + "Player can perform 3 actions: Move, Pick and Shoot\n" + "\n"
            + "Press the following keys to control player actions:\n"
            + "'m' - Move, 'p' - Pick, 's' - Shoot\n" + "\n"
            + "Press the following keys to select directions:\n"
            + "'n' - NORTH, 'w' - WEST, 'e' - EAST, 's' - SOUTH\n" + "\n"
            + "Press 'q' to quit the game.\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 4)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n"
            + "Moves: [NORTH, SOUTH, EAST, WEST]\n" + "Arrows: 0\n"
            + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n" + "Smell: FAINT\n"
            + "\n" + "Select player action:\n"
            + "Choose the direction in which player should move:\n" + "\n"
            + "Selected Action - Move, Direction - WEST\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 3)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [NORTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n" + "\n"
            + "Selected Action - Pick\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 3)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n" + "Moves: [NORTH, EAST, WEST]\n"
            + "Arrows: 0\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "Smell: PUNGENT\n" + "\n" + "Select player action:\n" + "\n"
            + "Ran out of inputs, Quitting game.\n";
    assertEquals(expected, output.toString());

    setup(new StringReader("s w 1 q"));
    controller.playGame();
    expected = "\n"
            + "Player can perform 3 actions: Move, Pick and Shoot\n" + "\n"
            + "Press the following keys to control player actions:\n"
            + "'m' - Move, 'p' - Pick, 's' - Shoot\n" + "\n"
            + "Press the following keys to select directions:\n"
            + "'n' - NORTH, 'w' - WEST, 'e' - EAST, 's' - SOUTH\n" + "\n"
            + "Press 'q' to quit the game.\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 4)\n"
            + "Arrows: 3\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n"
            + "Moves: [NORTH, SOUTH, EAST, WEST]\n" + "Arrows: 0\n"
            + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n" + "Smell: FAINT\n"
            + "\n" + "Select player action:\n"
            + "Enter the direction in which arrow should be shot:\n"
            + "Enter the distance the arrow should travel:\n" + "\n"
            + "Selected Action - Shoot, Direction - WEST, Distance - 1\n"
            + "Shot: MISS\n" + "\n"
            + "----------------------------------------------------------------\n"
            + "\n" + "Player Description:\n" + "Location: (1, 4)\n"
            + "Arrows: 2\n" + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n"
            + "\n" + "Location Description:\n"
            + "Moves: [NORTH, SOUTH, EAST, WEST]\n" + "Arrows: 0\n"
            + "Treasure: DIAMOND: 0, SAPPHIRE: 0, RUBY: 0\n" + "Smell: FAINT\n"
            + "\n" + "Select player action:\n" + "\n" + "Game Quit!!!\n";
    assertEquals(expected, output.toString());
  }


}